# Generated by Django 5.2.1 on 2025-08-18 13:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', 'Division I'), ('2', 'Division II'), ('3', 'Division III'), ('4', 'Division IV'), ('0', 'Failed')], max_length=1, unique=True)),
                ('min_points', models.IntegerField()),
                ('max_points', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['min_points'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('min_score', models.IntegerField()),
                ('max_score', models.IntegerField()),
                ('grade_point', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='Secondary School', max_length=100)),
                ('current_term', models.CharField(default='Term 1', max_length=50)),
                ('academic_year', models.CharField(default='2024', max_length=20)),
                ('report_title', models.CharField(default='Academic Report', max_length=100)),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('school_motto', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('category', models.CharField(choices=[('CORE', 'Core Subject'), ('SCIENCE', 'Science Options'), ('ARTS', 'Arts Options'), ('TECH', 'Technical Subjects'), ('LANG', 'Languages')], default='CORE', max_length=10)),
                ('is_elective', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_sent_messages', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_received_messages', to='secondary_dashboard.parent')),
            ],
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', 'Form 1'), ('2', 'Form 2'), ('3', 'Form 3'), ('4', 'Form 4')], help_text='The form level, e.g., Form 1', max_length=10)),
                ('class_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_of', to=settings.AUTH_USER_MODEL)),
                ('stream', models.ForeignKey(blank=True, help_text='The stream, e.g., North, South', null=True, on_delete=django.db.models.deletion.SET_NULL, to='secondary_dashboard.stream')),
                ('subjects', models.ManyToManyField(blank=True, to='secondary_dashboard.subject')),
            ],
            options={
                'verbose_name': 'Student Class',
                'verbose_name_plural': 'Student Classes',
                'unique_together': {('name', 'stream')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('admission_date', models.DateField(auto_now_add=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='student_profiles/')),
                ('medical_info', models.TextField(blank=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='secondary_dashboard.parent')),
                ('student_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='secondary_dashboard.studentclass')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=4)),
                ('total_points', models.IntegerField(default=0)),
                ('overall_position', models.IntegerField(blank=True, null=True)),
                ('stream_position', models.IntegerField(blank=True, null=True)),
                ('class_teacher_comment', models.TextField(blank=True)),
                ('headteacher_comment', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secondary_dashboard.examdivision')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='secondary_dashboard.student')),
            ],
            options={
                'unique_together': {('student', 'term', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=4)),
                ('assessment_type', models.CharField(choices=[('CAT1', 'Continuous Assessment Test 1'), ('CAT2', 'Continuous Assessment Test 2'), ('EXAM', 'End of Term Exam')], default='EXAM', max_length=4)),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secondary_dashboard.grade')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='secondary_dashboard.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondary_dashboard.subject')),
            ],
            options={
                'unique_together': {('student', 'subject', 'term', 'year', 'assessment_type')},
            },
        ),
    ]
