# Generated by Django 5.2.1 on 2025-08-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='name',
            field=models.CharField(choices=[('1', 'Form 1'), ('2', 'Form 2'), ('3', 'Form 3'), ('4', 'Form 4'), ('5', 'Form 5'), ('6', 'Form 6')], help_text='The form level, e.g., Form 1', max_length=10),
        ),
    ]
