# Generated by Django 5.2.1 on 2025-08-18 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary_dashboard', '0002_alter_studentclass_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentclass',
            options={'verbose_name': 'Form', 'verbose_name_plural': 'Forms'},
        ),
    ]
