# Generated by Django 5.2.1 on 2025-08-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary_dashboard', '0004_division_teachersignature'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='remarks',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
