# Generated by Django 5.2.1 on 2025-08-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary_dashboard', '0005_grade_remarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolsettings',
            old_name='school_logo',
            new_name='logo',
        ),
        migrations.RemoveField(
            model_name='schoolsettings',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='schoolsettings',
            name='report_title',
        ),
        migrations.RemoveField(
            model_name='schoolsettings',
            name='school_motto',
        ),
        migrations.RemoveField(
            model_name='schoolsettings',
            name='school_name',
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='current_year',
            field=models.PositiveIntegerField(blank=True, help_text='e.g., 2024', null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='name',
            field=models.CharField(default='School Name', max_length=255),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='current_term',
            field=models.CharField(blank=True, help_text='e.g., Term 1, Semester 2', max_length=20),
        ),
    ]
