# Generated by Django 5.2.1 on 2025-08-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary_dashboard', '0006_rename_school_logo_schoolsettings_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='school_motto',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
