# Generated by Django 5.2.5 on 2025-09-19 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary_dashboard', '0007_schoolsettings_school_motto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='headteacher_comment',
            new_name='principal_comment',
        ),
    ]
