# Generated by Django 5.2.5 on 2025-09-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary_dashboard', '0008_rename_headteacher_comment_report_principal_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
