# Generated by Django 5.2.5 on 2025-10-03 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary_dashboard', '0009_message_is_delivered'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('event_type', models.CharField(choices=[('graduation', 'Graduation'), ('meeting', 'Parent-Teacher Meeting'), ('sports', 'Sports Event'), ('cultural', 'Cultural Event'), ('exam', 'Exam Related'), ('holiday', 'Holiday/Closure'), ('other', 'Other')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
