# Generated by Django 5.2.5 on 2025-11-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary_dashboard', '0013_documentupload_target_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='form',
            field=models.CharField(choices=[('1', 'Form 1'), ('2', 'Form 2'), ('3', 'Form 3'), ('4', 'Form 4'), ('5', 'Form 5'), ('6', 'Form 6'), ('7', 'Form 7')], max_length=1),
        ),
    ]
