# Generated by Django 5.2.1 on 2025-11-05 20:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary_dashboard', '0015_alter_timetable_uploaded_by_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='secondary_notifications_read', to=settings.AUTH_USER_MODEL),
        ),
    ]
