# Generated by Django 5.2.4 on 2025-08-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_teacher_date_of_birth_alter_teacher_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='tsc_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='TSC Number'),
        ),
    ]
