# Generated by Django 5.2.4 on 2025-08-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_teacher_current_school_alter_teacher_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='school_level',
            field=models.CharField(blank=True, choices=[('primary', 'Primary School'), ('secondary', 'Secondary School')], max_length=10, null=True),
        ),
    ]
