# Generated by Django 5.2.4 on 2025-08-06 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=4)),
                ('class_teacher_comment', models.TextField(blank=True)),
                ('headteacher_comment', models.TextField(blank=True)),
                ('class_teacher_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('headteacher_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='primary_dashboard.student')),
            ],
            options={
                'unique_together': {('student', 'term', 'year')},
            },
        ),
        migrations.DeleteModel(
            name='ReportComment',
        ),
    ]
