# Generated by Django 5.2.5 on 2025-08-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_dashboard', '0003_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolsettings',
            old_name='school_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='schoolsettings',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='schoolsettings',
            name='current_term',
        ),
        migrations.RemoveField(
            model_name='schoolsettings',
            name='report_title',
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='school_logos/'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='school_motto',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
