# Generated by Django 5.2.5 on 2025-09-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_dashboard', '0004_rename_school_name_schoolsettings_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='term',
            field=models.CharField(blank=True, default='Term 1', max_length=20),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='year',
            field=models.CharField(blank=True, default='2025', max_length=4),
        ),
    ]
