# Generated by Django 5.2.5 on 2025-09-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_dashboard', '0005_schoolsettings_term_schoolsettings_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='middle_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='middle_name',
            field=models.CharField(max_length=50),
        ),
    ]
