# Generated by Django 5.2.5 on 2025-09-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_dashboard', '0007_message_is_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
