# Generated by Django 5.2.5 on 2025-11-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_dashboard', '0013_notification_read_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
